// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq88j9smhKxrxBbz6EbLgWCCPtTaWoWy4',
    appId: '1:843412624121:web:30fc18df07c65b899d8828',
    messagingSenderId: '843412624121',
    projectId: 'authapp-8f6f2',
    authDomain: 'authapp-8f6f2.firebaseapp.com',
    storageBucket: 'authapp-8f6f2.appspot.com',
    measurementId: 'G-EVVJBZLPMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4AoihXDH70hRKGu8BpOJ7Y_lVO5L7jao',
    appId: '1:843412624121:android:77eaa4d1f38286c39d8828',
    messagingSenderId: '843412624121',
    projectId: 'authapp-8f6f2',
    storageBucket: 'authapp-8f6f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5arbwUOD0i1QjAwO_IUnsXbrDXf2NbxE',
    appId: '1:843412624121:ios:335f491dd7f672cb9d8828',
    messagingSenderId: '843412624121',
    projectId: 'authapp-8f6f2',
    storageBucket: 'authapp-8f6f2.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5arbwUOD0i1QjAwO_IUnsXbrDXf2NbxE',
    appId: '1:843412624121:ios:335f491dd7f672cb9d8828',
    messagingSenderId: '843412624121',
    projectId: 'authapp-8f6f2',
    storageBucket: 'authapp-8f6f2.appspot.com',
    iosBundleId: 'com.example.firebaseAuthzzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq88j9smhKxrxBbz6EbLgWCCPtTaWoWy4',
    appId: '1:843412624121:web:941a667dbbdfddc09d8828',
    messagingSenderId: '843412624121',
    projectId: 'authapp-8f6f2',
    authDomain: 'authapp-8f6f2.firebaseapp.com',
    storageBucket: 'authapp-8f6f2.appspot.com',
    measurementId: 'G-25KL56LSVE',
  );
}
